INSERT INTO DEPARTMENT(ID, DEPARTMENT_NAME)VALUES(1001,'HR');
INSERT INTO DEPARTMENT(ID, DEPARTMENT_NAME)VALUES(1002,'IT');

INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(1001, NULL, 'John', 'Doe', 1001);
INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(1002, NULL, 'Eden', 'Hazard', 1001);
INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(1003, NULL, 'Romelu', 'Lukaku', 1002);