INSERT INTO DEPARTMENT(ID, DEPARTMENT_NAME)VALUES(1,'HR');
INSERT INTO DEPARTMENT(ID, DEPARTMENT_NAME)VALUES(2,'IT');

INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(1, NULL, 'John', 'Doe', 1);
INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(2, NULL, 'Eden', 'Hazard', 1);
INSERT INTO EMPLOYEE(ID, BIRTH_DATE, FIRST_NAME,LAST_NAME, DEPARTMENT_ID )VALUES(3, NULL, 'Romelu', 'Lukaku', 2);