CREATE TABLE IF NOT EXISTS DEPARTMENT (
  ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  DEPARTMENT_ID INT(6) UNSIGNED,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

